convert to hybrid rsync for snapshots and current, rclone for historic .. and cache each release separately vs all in one go, yeesh

diff --git a/oblocate b/oblocate
--- a/oblocate
+++ b/oblocate
@@ -35,10 +35,7 @@ export sort="env LC_ALL=C sort -H -S ${sortmem}M -T $TMPDIR"
 td=$(mktemp -d $TMPDIR/.${me}.XXXXXXXXXXXXXXXXXXXX)
 trap 'rm -rf $td' 0 1 2 3 13 15
 
-allincomp=allobsd.xz
-freqincomp=freqobsd.xz
-mirror=rsync://mirror.esc7.net/openbsd
-mirror=rsync://ftp.eu.openbsd.org/OpenBSD
+cachedir=$HOME/.cache/${me}
 
 cd $datadir || exit 1
 
@@ -56,25 +53,87 @@ if [ build -eq 0 ]; then
 	exec locate -d $datadir/$dbname "$@"
 fi
 
+
+RPATHS=""
+
+addrpath() {
+	RPATHS="$1 $RPATHS"
+}
+
+# last takes precedence
+addrpath "rsync://mirror.esc7.net/openbsd"
+addrpath "rsync://ftp.spline.de/OpenBSD"
+addrpath "rsync://ftp.hostserver.de/OpenBSD"
+addrpath "rsync://ftp.usa.openbsd.org/ftp"
+addrpath "rsync://mirror.planetunix.net/OpenBSD/"
+addrpath "rsync://mirror.leaseweb.com/openbsd/"
+
+mkdir -p $cachedir
+
 compress() {
 	xz -9
 }
-if ! [ -f $allincomp ]; then
-	updateall=1
-else
-	if [ "$(find $allincomp -mtime +30)" ]; then
-		updateall=1
-	fi
-fi
-if [ updateall -eq 1 ]; then
-	# update once every 30 days 'everything'
-	# XXX once verified it works right, add stripall below
-	rsync -rl --exclude='\.\~tmp\~' $mirror/. 2> /dev/null | compress > .$allincomp && \
-		mv -f .$allincomp $allincomp || exit 1
-fi
+rsync_lsrmt() {
+	rsync --no-motd $RPATH/"$1" | \
+	awk '{
+		type="/";
+		if (substr($1,1,1) == "-") {
+			type=""
+		};
+		if($5 == ".") {
+			next
+		};
+		printf "%s%s\n", $5, type}'
+}
+rclone_lsrmt() {
+	rclone lsd ob-http:"$1" | \
+	awk '{
+		printf "%s/\n", $5, type}'
+}
 
-mungeforlocate() {
-	awk '
+err="@ERROR: max connections ([0-9]+) reached -- try again later"
+for p in $RPATHS
+do
+	echo "Testing $p"
+	if [ "$(rsync --no-motd -l $p/snapshots/amd64/index.txt 2>&1 | egrep "$err")" ]
+	then
+		continue
+	fi
+	RPATH="$p"
+	break
+done
+
+rsync_cache_dir() {
+	local d="$1"
+	local dname="$(echo "$d"|sed 's,/,_,g')"
+	echo "caching rmt dir $d"
+	rsync --no-motd -rl --exclude='\.\~tmp\~' $RPATH/${d}/. 2> /dev/null | \
+	rsync_mungeforlocate "$d" | \
+	compress > ${cachedir}/.${dname}.xz && \
+	mv -f ${cachedir}/.${dname}.xz ${cachedir}/${dname}.xz || exit 1
+}
+rclone_cache_dir() {
+	local d="$1"
+	local dname="$(echo "$d"|sed 's,/,_,g')"
+	echo "caching rmt dir $d"
+	rclone lsl ob-http:${d} 2> /dev/null | \
+	rclone_mungeforlocate "$d" | \
+	compress > ${cachedir}/.${dname}.xz && \
+	mv -f ${cachedir}/.${dname}.xz ${cachedir}/${dname}.xz || exit 1
+}
+	
+rclone_mungeforlocate() {
+	awk -v d="$1" '
+		{
+			gsub("-","",$2);
+			gsub(":","",$3);
+			gsub("\\.[0-9]+","",$3);
+			printf "%s%s|%x|%s/%s\n",$2,$3,$1,d,$4;
+		}'
+}
+
+rsync_mungeforlocate() {
+	awk -v d="$1" '
 	/\~$/		{next}
 	$5 ~ /^\.$/	{next}
 	! /^[-d]/	{next}
@@ -84,25 +143,32 @@ mungeforlocate() {
 				gsub(",","",$2);
 				gsub("/","",$3);
 				gsub(":","",$4);
-				printf "%s%s|%x|%s%s\n",$3,$4,$2,$5,t;
+				printf "%s%s|%x|%s/%s%s\n",$3,$4,$2,d,$5,t;
 			}'
 }
+
+# should be static, rm to refresh
+for d in $(rclone_lsrmt | egrep "^[0-9].[0-9]/$")
+do
+	d=${d%*/}
+	dname="$(echo "$d"|sed 's,/,_,g')"
+	if ! [ -f $cachedir/${dname}.xz ]; then
+		rclone_cache_dir "$d"
+	fi
+done
 
 # strip freq dirs off 'all' bits
 stripall() {
 	awk '/ (ftplist|timestamp|Changelogs|OpenSSH\/portable|patches|snapshots)/{next}{print}'
 }
 
-# update a few more frequently updated bits every night
-for url in $mirror/{ftplist,timestamp,Changelogs,OpenSSH/portable,patches,snapshots}
+# update each time
+for path in {ftplist,timestamp,Changelogs,OpenSSH/portable,patches,snapshots}
 do
-	rsync -rl --exclude='\.\~tmp\~' $url 2> /dev/null
-done | compress > .$freqincomp && \
-	mv -f .$freqincomp $freqincomp
+	rsync_cache_dir "$path"
+done 
 
-{
-	xz -d < $allincomp | stripall
-	xz -d < $freqincomp
-} | $sort -u | mungeforlocate | \
+xzcat $cachedir/*.xz | \
+	$sort -u | \
 	/usr/libexec/locate.mklocatedb > .$dbname && \
 	mv -f .$dbname $dbname
